### ISSUE TITLE
Any thought to creating a Homebrew package for this?

### ISSUE THREAD

**Issue by chrismetcalf** [BestPig/cv#1]
https://github.com/Homebrew/homebrew/wiki/Formula-Cookbook

:beer:

**Comment by BestPig** [comment]
I just have send the pull request to Homebrew
https://github.com/Homebrew/homebrew/pull/32161

**Comment by chrismetcalf** [comment]
Awesome, thanks!

**Comment by techniq** [comment]
:+1:

**Comment by BestPig** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/progress.rb
